version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-service
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
